- name: Sealed-Secret Namespace
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('file', 'files/sealed-secrets-ns.yaml') }}"

- name: Sealed-Secret Operator Group
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('file', 'files/sealed-secrets-og.yaml') }}"

- name: Sealed-Secret Subscription
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('file', 'files/sealed-secrets-subscr.yaml') }}"

- name: wait for sealed-secrets CRD to be available
  k8s_info:
    validate_certs: no
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: sealedsecretcontrollers.bitnami.com
  register: sealedsecretcontrollers_crd
  until: sealedsecretcontrollers_crd.resources | length > 0
  retries: 20
  delay: 5

- name: Sealed-Secret Controller
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('template', 'templates/sealed-secrets-controller.yaml.j2') }}"

- name: Download kubeseal binary
  become: True
  get_url:
    url: "{{ sealed_secrets_kubeseal_downloadurl }}"
    dest: "/usr/local/bin/kubeseal"
    mode: 0755
    force: yes  
