apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: env-app-project
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Permit applications to deploy to any namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace, ClusterRole, and ClusterRoleBinding
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: ClusterRole
  - group: ''
    kind: ClusterRoleBinding
  # Allow all namespaced-scoped resources to be created, except for NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: NetworkPolicy
