apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apache-ns

bases:
  - ../../../definitions/APP1/DEV/quotas-limits

resources:
  - namespace.yaml
  - openshift-gitops-argocd-admin-rolebinding.yaml
