apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: env-app-project
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Definitions for other projects
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Permit applications to deploy to any namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  # Allow creation of all cluster-scoped resources
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
