kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: environment-definitions
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: env-app-project
  source:
    path: overlays/environment/openshift-gitops
    repoURL: https://github.com/manurodriguez/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
