apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project2

bases:
  - ../../../definitions/APP2/DEV/quotas-limits
  - ../../../definitions/APP2/DEV/rbac-bindings

resources:
  - namespace.yaml

